# Generated by Django 4.0.4 on 2022-06-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('A', 'Admin'), ('E', 'Expert'), ('S', 'Student')], max_length=1)),
            ],
        ),
    ]
