# Generated by Django 4.0.4 on 2022-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_expert_status_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='LoginT',
        ),
    ]
