# Generated by Django 4.0.4 on 2022-06-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_student_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.DateTimeField()),
                ('allot_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.expert')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.student')),
            ],
        ),
    ]
