# Generated by Django 4.0.4 on 2022-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_studentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='allot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
