# Generated by Django 4.0.4 on 2022-06-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_studentrequest_allot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.expert')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.student')),
            ],
        ),
    ]
