# Generated by Django 4.0.4 on 2022-06-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('task_file', models.FileField(upload_to='tasks')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='tasks')),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('W', 'Waiting'), ('V', 'Verified'), ('R', 'Resubmit')], max_length=1, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.classroom')),
            ],
        ),
    ]
