# Generated by Django 4.0.4 on 2022-06-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=90)),
                ('answer', models.CharField(max_length=90)),
                ('status', models.CharField(blank=True, choices=[('W', 'Waiting'), ('A', 'Answered')], max_length=1, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.classroom')),
            ],
        ),
    ]
